[build]
  # Build command for Astro frontend
  command = "cd frontend && npm install && npm run build"
  
  # Publish directory (Astro output)
  publish = "frontend/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "20.19.0"
  
  # Build environment
  NODE_ENV = "production"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Environment variables for frontend
[context.production.environment]
  PUBLIC_SUPABASE_URL = "your_supabase_url"
  PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  PUBLIC_API_URL = "your_backend_api_url"

[context.deploy-preview.environment]
  PUBLIC_SUPABASE_URL = "your_supabase_url"
  PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  PUBLIC_API_URL = "your_backend_api_url"

[context.branch-deploy.environment]
  PUBLIC_SUPABASE_URL = "your_supabase_url"
  PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  PUBLIC_API_URL = "your_backend_api_url"

# Functions (if needed for serverless functions)
[functions]
  directory = "frontend/functions"

# Edge functions (if needed)
[edge_functions]
  directory = "frontend/edge-functions"

# Form handling
[[redirects]]
  from = "/api/submit-reservation"
  to = "/.netlify/functions/submit-reservation"
  status = 200

# Health check endpoint
[[redirects]]
  from = "/health"
  to = "/api/health"
  status = 200

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200
  force = true 